import type { Metadata } from "next";
import { Container, Eyebrow } from "@/components/ui";
import { site } from "@/lib/site";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: `How ${site.name} collects, uses and protects personal information.`,
  alternates: { canonical: "/privacy" },
  robots: { index: false, follow: true },
};

const sections = [
  {
    title: "Who this policy covers",
    body: [
      `${site.legalName} controls the personal information described in this policy when you visit ${site.domain}, contact us on WhatsApp, submit an enquiry, review or electronically approve an agreement, receive an invoice, or work with us on a project.`,
      `Questions and privacy requests may be sent to ${site.email} or raised by WhatsApp at ${site.phone}.`,
    ],
  },
  {
    title: "Information we collect",
    body: [
      "Enquiries and WhatsApp leads may include your name, phone number, email, company, website, budget, timeline, selected services, messages and project requirements.",
      "Deal records may include proposals, contract versions, comments, approvals, typed electronic signatures, invoice details, payment status, project notes and kickoff checklists.",
      "For the integrity of an electronic approval we record the agreement version, a cryptographic document fingerprint, signature name, time, browser information and a one-way hash of the network address. We do not display the raw network address in the admin panel.",
      "If you accept optional analytics cookies, we may receive page, device, referral and approximate location information from the configured analytics providers. We do not activate those analytics before consent.",
    ],
  },
  {
    title: "Why we use information",
    body: [
      "We use information to answer enquiries, communicate through WhatsApp or email, prepare proposals and contracts, record client decisions, issue invoices, collect payment, deliver projects, provide support, prevent abuse and maintain business records.",
      "Depending on the context and your location, processing is based on steps requested before a contract, performance of a contract, compliance with legal obligations, consent for optional analytics, or our legitimate interests in operating and securing the business. You may withdraw consent without affecting earlier lawful processing.",
    ],
  },
  {
    title: "Service providers and international transfers",
    body: [
      "We do not sell personal information. We disclose only what is reasonably needed to hosting and infrastructure providers, professional advisers, communication services such as WhatsApp, banks involved in a transfer, and authorities where legally required.",
      "Google Analytics and Microsoft Clarity receive analytics data only after consent and only when their identifiers are configured. When an administrator deliberately uses AI proposal refinement, relevant enquiry and draft content may be sent to the configured AI provider; prices, legal decisions and signatures are not generated by that service.",
      "Providers may process information outside your country. Where required, we use contractual and organisational safeguards appropriate to the transfer and provider relationship.",
    ],
  },
  {
    title: "Payments",
    body: [
      "Current invoices are settled by bank transfer after contract signing. Bank details are shared directly through the agreed secure channel and are not published on the website. Online payment providers may be added in a future policy update.",
    ],
  },
  {
    title: "Retention",
    body: [
      "Unconverted enquiries are normally reviewed for deletion or anonymisation after 24 months. Contracts, approvals, invoices and related commercial records may be kept for up to seven years after the relationship ends, or longer where law, an active dispute or a client obligation requires it. Security logs are retained only for a proportionate operational period.",
    ],
  },
  {
    title: "Security",
    body: [
      "We use encryption for stored enquiry, contract and invoice payloads, signed and HttpOnly admin sessions, access controls, rate limits and restricted private links. No internet service can guarantee absolute security; suspected incidents are investigated and handled according to applicable obligations.",
    ],
  },
  {
    title: "Your choices and rights",
    body: [
      `Depending on your location, you may request access, correction, deletion, restriction, objection, portability or withdrawal of consent by contacting ${site.email}. We may need to verify your identity and may retain information where a legal or contractual exception applies.`,
    ],
  },
  {
    title: "Cookies",
    body: [
      "Essential cookies support secure admin sessions and core preferences. Optional Google Analytics or Microsoft Clarity scripts load only after you select Accept. Your choice is stored in your browser; clearing site storage lets you choose again.",
    ],
  },
  {
    title: "Children and policy changes",
    body: [
      "Our business services are not directed to children. Please do not provide a child's personal information through the enquiry or contract workflow.",
      "We may update this policy when our services or providers change. The date on this page identifies the current version; material changes will be presented through an appropriate notice.",
    ],
  },
];

export default function PrivacyPage() {
  return (
    <section className="py-20 sm:py-24">
      <Container>
        <div className="mx-auto max-w-2xl">
          <Eyebrow>Legal</Eyebrow>
          <h1 className="mt-6 text-4xl font-semibold leading-tight sm:text-5xl">
            Privacy Policy
          </h1>
          <p className="mt-4 text-sm text-faint">
            Last updated: 22 August 2026
          </p>

          <div className="mt-12 space-y-10">
            {sections.map((s) => (
              <div key={s.title} id={s.title === "Cookies" ? "cookies" : undefined} className="scroll-mt-24">
                <h2 className="text-xl font-semibold">{s.title}</h2>
                <div className="mt-3 space-y-3">
                  {s.body.map((p, i) => (
                    <p key={i} className="text-[0.98rem] leading-[1.75] text-muted">
                      {p}
                    </p>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </div>
      </Container>
    </section>
  );
}
