"use client";

import { Icon } from "./Icon";
import { useState } from "react";

export function ProposalActions({ email, token }: { email: string; token: string }) {
  const [open, setOpen] = useState(false); const [sent, setSent] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function respond(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); const form = new FormData(event.currentTarget); const payload = { ...Object.fromEntries(form.entries()), accepted: form.get("accepted") === "on" }; const response = await fetch(`/api/proposals/${token}/feedback`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const result = await response.json().catch(() => ({})); if (response.ok) { setSent(true); setOpen(false); } else setError(result.error || "Could not send your response."); setBusy(false); }
  return <div className="no-print sticky top-0 z-20 border-b border-white/10 bg-[#0b0b0c]/95 px-5 py-3 text-white backdrop-blur"><div className="mx-auto max-w-4xl"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-semibold">Private CINEM agreement</p><p className="text-xs text-white/50">{sent ? "Your response has been recorded." : "Review, comment, approve or download"}</p></div><div className="flex flex-wrap gap-2"><button onClick={() => setOpen((value) => !value)} className="rounded-full border border-white/15 px-4 py-2 text-xs font-semibold hover:bg-white/10">Respond / e-sign</button><button type="button" onClick={() => window.print()} className="inline-flex items-center gap-2 rounded-full bg-white px-4 py-2 text-xs font-semibold text-black"><Icon name="arrow" className="h-3.5 w-3.5 rotate-90" /> Save PDF / Print</button></div></div>{open ? <form onSubmit={respond} className="mt-4 grid gap-3 border-t border-white/10 pt-4 sm:grid-cols-2"><input name="name" required placeholder="Your name" className="rounded-xl border border-white/15 bg-white/5 px-3 py-2 text-sm" /><input name="email" type="email" required defaultValue={email} placeholder="Your email" className="rounded-xl border border-white/15 bg-white/5 px-3 py-2 text-sm" /><select name="type" className="rounded-xl border border-white/15 bg-[#18181a] px-3 py-2 text-sm"><option value="approved">Approve and electronically sign</option><option value="changes_requested">Request changes</option><option value="comment">Leave a comment</option></select><input name="message" placeholder="Comment or requested change" className="rounded-xl border border-white/15 bg-white/5 px-3 py-2 text-sm" /><input name="signatureName" placeholder="Type full legal name to sign" className="rounded-xl border border-white/15 bg-white/5 px-3 py-2 text-sm sm:col-span-2" /><label className="flex items-start gap-2 text-xs leading-5 text-white/70 sm:col-span-2"><input name="accepted" type="checkbox" className="mt-1" /> I intend to sign electronically and agree that my typed name records my approval of this exact agreement version.</label>{error ? <p className="text-xs text-red-300 sm:col-span-2">{error}</p> : null}<button disabled={busy} className="rounded-xl bg-white px-4 py-2 text-sm font-semibold text-black sm:col-span-2">{busy ? "Recording…" : "Submit secure response"}</button></form> : null}</div></div>;
}
