import Database from "better-sqlite3";
import { createCipheriv, createDecipheriv, randomBytes, randomUUID } from "node:crypto";
import path from "node:path";
import { getContract } from "./contracts";

export type InvoiceStatus = "draft" | "sent" | "paid";
export type InvoiceData = { clientName: string; clientCompany: string; clientEmail: string; clientPhone: string; currency: string; amount: string; description: string; issueDate: string; dueDate: string; notes: string };
export type InvoiceRecord = { id: string; contractId: string; number: string; shareToken: string; status: InvoiceStatus; createdAt: string; updatedAt: string; data: InvoiceData };
type Row = { id: string; contract_id: string; invoice_number: string; share_token: string; status: InvoiceStatus; created_at: string; updated_at: string; payload: string };
const globalDb = globalThis as typeof globalThis & { __cinemInvoiceDb?: Database.Database };
function db() { if (globalDb.__cinemInvoiceDb) return globalDb.__cinemInvoiceDb; const value = new Database(process.env.CINEM_DB_PATH || path.join(process.cwd(), "data", "cinem.sqlite")); value.pragma("journal_mode = WAL"); value.exec(`CREATE TABLE IF NOT EXISTS invoices (id TEXT PRIMARY KEY, contract_id TEXT NOT NULL, invoice_number TEXT NOT NULL UNIQUE, share_token TEXT NOT NULL UNIQUE, status TEXT NOT NULL CHECK(status IN ('draft','sent','paid')), created_at TEXT NOT NULL, updated_at TEXT NOT NULL, payload TEXT NOT NULL); CREATE INDEX IF NOT EXISTS invoice_contract_idx ON invoices(contract_id);`); globalDb.__cinemInvoiceDb = value; return value; }
function key() { const value = Buffer.from(process.env.ENQUIRY_ENCRYPTION_KEY || "", "base64"); if (value.length !== 32) throw new Error("Invoice encryption key is not configured."); return value; }
function encrypt(data: InvoiceData) { const iv = randomBytes(12); const cipher = createCipheriv("aes-256-gcm", key(), iv); const body = Buffer.concat([cipher.update(JSON.stringify(data)), cipher.final()]); return ["v1", iv.toString("base64url"), cipher.getAuthTag().toString("base64url"), body.toString("base64url")].join("."); }
function decrypt(value: string) { const [, iv, tag, body] = value.split("."); const decipher = createDecipheriv("aes-256-gcm", key(), Buffer.from(iv, "base64url")); decipher.setAuthTag(Buffer.from(tag, "base64url")); return JSON.parse(Buffer.concat([decipher.update(Buffer.from(body, "base64url")), decipher.final()]).toString()) as InvoiceData; }
function map(row: Row): InvoiceRecord { const data=decrypt(row.payload); return { id: row.id, contractId: row.contract_id, number: row.invoice_number, shareToken: row.share_token, status: row.status, createdAt: row.created_at, updatedAt: row.updated_at, data: { ...data, clientPhone: data.clientPhone || "" } }; }
export function createInvoice(contractId: string) { const contract = getContract(contractId); if (!contract) return null; const now = new Date(); const due = new Date(now); due.setDate(due.getDate() + 7); const count = (db().prepare("SELECT COUNT(*) AS value FROM invoices").get() as { value: number }).value + 1; const record = { id: `inv_${randomUUID()}`, number: `CIN-${now.getFullYear()}-${String(count).padStart(4, "0")}`, token: randomBytes(24).toString("base64url"), created: now.toISOString(), data: { clientName: contract.data.clientName, clientCompany: contract.data.clientCompany, clientEmail: contract.data.clientEmail, clientPhone: contract.data.clientPhone, currency: contract.data.currency, amount: contract.data.totalFee, description: contract.data.projectTitle, issueDate: now.toISOString().slice(0, 10), dueDate: due.toISOString().slice(0, 10), notes: "Payment is due by bank transfer within seven calendar days. Bank details will be shared directly after contract signing through the agreed secure channel." } }; db().prepare("INSERT INTO invoices VALUES (?, ?, ?, ?, 'draft', ?, ?, ?)").run(record.id, contractId, record.number, record.token, record.created, record.created, encrypt(record.data)); return getInvoice(record.id); }
export function getInvoice(id: string) { const row = db().prepare("SELECT * FROM invoices WHERE id = ?").get(id) as Row | undefined; return row ? map(row) : null; }
export function getSharedInvoice(token: string) { const row = db().prepare("SELECT * FROM invoices WHERE share_token = ? AND status IN ('sent','paid')").get(token) as Row | undefined; return row ? map(row) : null; }
export function updateInvoice(id: string, input: { data?: InvoiceData; status?: InvoiceStatus }) { const current = getInvoice(id); if (!current) return null; const data = input.data ? Object.fromEntries(Object.entries({ ...current.data, ...input.data }).map(([k, v]) => [k, typeof v === "string" ? v.trim().slice(0, 5000) : ""])) as unknown as InvoiceData : current.data; const status = input.status || current.status; if (status !== "draft" && (!data.clientEmail || !data.amount || !data.dueDate)) throw new Error("Client email, amount and due date are required before sending."); const updatedAt = new Date().toISOString(); db().prepare("UPDATE invoices SET status = ?, updated_at = ?, payload = ? WHERE id = ?").run(status, updatedAt, encrypt(data), id); return { ...current, status, updatedAt, data }; }
